const ADD_NEW_RECIPE = 'ADD_NEW_RECIPE';
const DELETE_RECIPE = 'DELETE_RECIPE';
const SELECT_RECIPE = 'SELECT_RECIPE';
const REQUEST_RECIPES = 'REQUEST_RECIPES';
const RECEIVE_RECIPES = 'RECEIVE_RECIPES';

export default {
    ADD_NEW_RECIPE,
    DELETE_RECIPE,
    SELECT_RECIPE,
    REQUEST_RECIPES,
    RECEIVE_RECIPES
}