const RECIPE_SELECTED = 'RECIPE_SELECTED';
const CREATE_NEW_RECIPE = 'CREATE_NEW_RECIPE';
const CANCEL_EDIT = "CANCEL_EDIT";

export default {
    RECIPE_SELECTED,
    CREATE_NEW_RECIPE,
    CANCEL_EDIT
}