const RECIPE_SELECTED = 'RECIPE_SELECTED';
const CREATE_NEW_RECIPE = 'CREATE_NEW_RECIPE';
const CANCEL_EDIT = "CANCEL_EDIT";
const RECIPE_DELETED = 'RECIPE_DELETED';
const EDIT_RECIPE = 'EDIT_RECIPE';
const RECIPE_UPDATED = 'RECIPE_UPDATED';

export default {
    RECIPE_SELECTED,
    RECIPE_UPDATED,
    CREATE_NEW_RECIPE,
    CANCEL_EDIT,
    RECIPE_DELETED,
    EDIT_RECIPE,
}